/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DeleteStudent.java
 *
 * Created on Sep 28, 2010, 5:40:37 PM
 */

package hostelmanagementsystem;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Shreeyash
 */
public class DeleteStudent extends javax.swing.JInternalFrame {

    /** Creates new form DeleteStudent */
    public DeleteStudent() {
        super("Delete Student Information",false,true,false);
        initComponents();
        this.setVisible(true);
        this.setIconifiable(true);
        try
        {
        DBConnectivity dbc = new DBConnectivity();
        ResultSet rs = dbc.selectQuery("select stud_id from StudentMaster");
        while(rs.next())
        {
           //rs.getInt(1);
           studid.addItem(rs.getInt(1));
        }
        dbc.closeConnection();
        }
        catch(Exception e){}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infopanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addr = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        phno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        course = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        college = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        contactno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        no = new javax.swing.JRadioButton();
        yes = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        rmno = new javax.swing.JTextField();
        delete_button = new javax.swing.JButton();
        update_cancle = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        studid = new javax.swing.JComboBox();

        infopanel.setPreferredSize(new java.awt.Dimension(300, 400));

        jLabel1.setText("Student Name");

        jLabel2.setText(" Age");

        jLabel3.setText(" Date Of Birth");

        jLabel4.setText("Gender");

        male.setSelected(true);
        male.setText("Male");

        female.setText("Female");

        jLabel5.setText("Permanant Address");

        jScrollPane1.setMinimumSize(new java.awt.Dimension(6, 20));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(6, 20));

        addr.setColumns(20);
        addr.setRows(5);
        addr.setPreferredSize(new java.awt.Dimension(6, 20));
        jScrollPane1.setViewportView(addr);

        jLabel6.setText("Phone Number");

        jLabel7.setText("College Name");

        jLabel8.setText("Course Name");

        jLabel9.setText("Contact Name");

        jLabel10.setText("Physically Handicaped");

        no.setSelected(true);
        no.setText("No");

        yes.setText("Yes");

        jLabel11.setText("Room Number");

        delete_button.setText("Delete");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        update_cancle.setText("Cancle");
        update_cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_cancleActionPerformed(evt);
            }
        });

        jLabel12.setText("Select Student ID");

        studid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                studiditemChanged(evt);
            }
        });

        javax.swing.GroupLayout infopanelLayout = new javax.swing.GroupLayout(infopanel);
        infopanel.setLayout(infopanelLayout);
        infopanelLayout.setHorizontalGroup(
            infopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infopanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(infopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infopanelLayout.createSequentialGroup()
                        .addComponent(studid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(infopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(infopanelLayout.createSequentialGroup()
                            .addComponent(delete_button)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(update_cancle)
                            .addGap(202, 202, 202))
                        .addGroup(infopanelLayout.createSequentialGroup()
                            .addGroup(infopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(infopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dob)
                                    .addGroup(infopanelLayout.createSequentialGroup()
                                        .addComponent(male)
                                        .addGap(18, 18, 18)
                                        .addComponent(female))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(contactno, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                .addComponent(college, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                .addComponent(course, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                .addComponent(phno, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                .addGroup(infopanelLayout.createSequentialGroup()
                                    .addComponent(no)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(yes))
                                .addComponent(rmno, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(143, 143, 143)))))
        );
        infopanelLayout.setVerticalGroup(
            infopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infopanelLayout.createSequentialGroup()
                .addGroup(infopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(studid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(infopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(male)
                    .addComponent(female))
                .addGap(18, 18, 18)
                .addGroup(infopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(infopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(phno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(infopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(college, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(contactno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(no)
                    .addComponent(yes))
                .addGap(18, 18, 18)
                .addGroup(infopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rmno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete_button)
                    .addComponent(update_cancle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infopanel, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infopanel, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Do you want to continue?", "Confirm",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    if (response == JOptionPane.NO_OPTION) {
      System.out.println("No button clicked");
    } else if (response == JOptionPane.YES_OPTION) {
      System.out.println("Yes button clicked");
       try
        {
            String del_qry = "delete * from StudentMaster where stud_id="+Integer.parseInt(studid.getSelectedItem().toString());
            String update_room = "update RoomMaster set ID=0,  flag='1' where roomno='"+rmno.getText()+"'";
            DBConnectivity dbc = new DBConnectivity();
            int i = dbc.deleteQuery(del_qry);
            if(i == 1)
            {
                JOptionPane.showMessageDialog(null, "Value deleted succesfully");
            }
            dbc.updateQuery(update_room);
            dbc.closeConnection();
            this.setVisible(false);
        }
        catch(Exception e){System.out.println(e);}
    } else if (response == JOptionPane.CLOSED_OPTION) {
      System.out.println("JOptionPane closed");
    }
       
        /*String nm =  name.getText().trim();
        String ad = addr.getText().trim();
        String ag = age.getText().trim();
        String gndr;
        if(male.isSelected()) {
            gndr = "male";
        } else {
            gndr = "female";
        }
        String db = dob.getText().trim();
        String coll = college.getText().trim();
        String cours = course.getText().trim();
        String ph = phno.getText().trim();
        String cntno = contactno.getText().trim();
        String phyhand;
        if(no.isSelected()) {
            phyhand = "no";
        } else {
            phyhand = "yes";
        }
        String rm = rmno.getText();

        String update_stud = "update StudentMaster set name='"+nm+"',add='"+ad+"',age='"+ag+"',dob='"+db+"',gender='"+gndr+"',college='"+coll+"',course='"+cours+"',phone='"+ph+"',contactno='"+cntno+"',phy_hand='"+phyhand+"',roomno='"+rmno.getText()+"' where stud_id="+Integer.parseInt(studid.getSelectedItem().toString());

        String update_room = "update RoomMaster set roomno='"+rmno.getText()+"', flag=2 where ID="+Integer.parseInt(studid.getSelectedItem().toString());

        System.out.println(update_stud+"\n"+update_room);

        DBConnectivity dbc = new DBConnectivity();
        int is = dbc.updateQuery(update_stud);
        System.out.println("insert query = "+is);
        if(is == 1) {
            JOptionPane.showMessageDialog(null, "Value Updated succesfully");
            // this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Value not updated");
        }
        //String update_qry = "update RoomMaster set flag = '2' where roomno='"+rmno.getSelectedItem().toString()+"'";
        System.out.println(update_room);
        int u = dbc.updateQuery(update_room);
        if(u == 1) {
            //JOptionPane.showMessageDialog(null, "Value inserted succesfully");
            this.setVisible(false);
        } else {
            //JOptionPane.showMessageDialog(null, "Value not inserted");
        }
        dbc.closeConnection();*/

    }//GEN-LAST:event_delete_buttonActionPerformed

    private void update_cancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_cancleActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
}//GEN-LAST:event_update_cancleActionPerformed

    private void studiditemChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_studiditemChanged
        // TODO add your handling code here:
        String selected_item = studid.getSelectedItem().toString();
        System.out.println("selected item = "+selected_item);
        int id = Integer.parseInt(selected_item);
        try {
            DBConnectivity dbc = new DBConnectivity();
            ResultSet rs = dbc.selectQuery("select * from StudentMaster where stud_id="+id);
            while(rs.next()) {
                //rs.getInt(1);

                name.setText(rs.getString(2));
                age.setText(rs.getString(4));
                dob.setText(rs.getString(5));
                if(rs.getString(6).equals("male"))
                    male.setSelected(true);
                else
                    female.setSelected(false);
                addr.setText(rs.getString(3));
                phno.setText(rs.getString(9));
                course.setText(rs.getString(8));
                college.setText(rs.getString(7));
                contactno.setText(rs.getString(10));
                if(rs.getString(11).equals("no"))
                    no.setSelected(true);
                else
                    yes.setSelected(false);
                rmno.setText(rs.getString(12));
            }
            infopanel.setVisible(true);
            dbc.closeConnection();
        } catch(Exception e){}
}//GEN-LAST:event_studiditemChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addr;
    private javax.swing.JTextField age;
    private javax.swing.JTextField college;
    private javax.swing.JTextField contactno;
    private javax.swing.JTextField course;
    private javax.swing.JButton delete_button;
    private javax.swing.JTextField dob;
    private javax.swing.JRadioButton female;
    private javax.swing.JPanel infopanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private javax.swing.JRadioButton no;
    private javax.swing.JTextField phno;
    private javax.swing.JTextField rmno;
    private javax.swing.JComboBox studid;
    private javax.swing.JButton update_cancle;
    private javax.swing.JRadioButton yes;
    // End of variables declaration//GEN-END:variables

}
